apiVersion: v1
kind: Pod
metadata:
  name: pong
  labels:
    name: pong
spec:
  containers:
  - name: pong
    image: patrocinio/ping_pong
    env:
      - name: QUEUE
        value: "pong"
      - name: OTHER_QUEUE
        value: "ping"
